name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - main
    tags:
    - v*
  pull_request:
    branches:
    - main

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  main:
    uses: mrahhal/.github/.github/workflows/ci-dotnet-package.yml@main
    with:
      dotnet-version: 6.x.x
      dotnet-additional-version: 3.x.x
    secrets:
      NUGET_ORG_API_KEY: ${{ secrets.NUGET_ORG_API_KEY }}
